name = "bookmarker"
type = "javascript"
account_id = ""
workers_dev = true

[vars]
AUTH_KEY = ""
HASURA_ADMIN_SECRET = ""
HASURA_ENDPOINT = ""
TWITTER_KEY = ""
VIMEO_KEY = ""
YOUTUBE_KEY = ""

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
