name: Build and Deploy Worker

on: push

jobs:
  worker:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          VIMEO_KEY: ${{ secrets.VIMEO_KEY }}
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
